//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace publish.AllServices {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AllServices.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Top10ContentWords", ReplyAction="http://tempuri.org/IService1/Top10ContentWordsResponse")]
        string[] Top10ContentWords(string url);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Top10Words", ReplyAction="http://tempuri.org/IService1/Top10WordsResponse")]
        string[] Top10Words(string url);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/WordFilter", ReplyAction="http://tempuri.org/IService1/WordFilterResponse")]
        string WordFilter(string word);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Sort", ReplyAction="http://tempuri.org/IService1/SortResponse")]
        string Sort(string c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/palindrome", ReplyAction="http://tempuri.org/IService1/palindromeResponse")]
        int palindrome(string s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Stemming", ReplyAction="http://tempuri.org/IService1/StemmingResponse")]
        string Stemming(string input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/deleteChar", ReplyAction="http://tempuri.org/IService1/deleteCharResponse")]
        string deleteChar(string s1, string s2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Permutation", ReplyAction="http://tempuri.org/IService1/PermutationResponse")]
        string[] Permutation(string input);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : publish.AllServices.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<publish.AllServices.IService1>, publish.AllServices.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] Top10ContentWords(string url) {
            return base.Channel.Top10ContentWords(url);
        }
        
        public string[] Top10Words(string url) {
            return base.Channel.Top10Words(url);
        }
        
        public string WordFilter(string word) {
            return base.Channel.WordFilter(word);
        }
        
        public string Sort(string c) {
            return base.Channel.Sort(c);
        }
        
        public int palindrome(string s) {
            return base.Channel.palindrome(s);
        }
        
        public string Stemming(string input) {
            return base.Channel.Stemming(input);
        }
        
        public string deleteChar(string s1, string s2) {
            return base.Channel.deleteChar(s1, s2);
        }
        
        public string[] Permutation(string input) {
            return base.Channel.Permutation(input);
        }
    }
}
